baseURL: ''
languageCode: en-us
title: strawhattom
theme: PaperMod

languages:
  en:
    languageName: English
    title: strawhattom
    weight: 1
  fr:
    languageName : Français    
    title: strawhattom
    weight: 2

cover:
  hidden: false # hide everywhere but not in structured data
  hiddenInList: false # hide on list pages and home
  hiddenInSingle: false # hide on single page
params:
  homeInfoParams:
    Title: 'Welcome to my portfolio'
    Content: 'I am Tom X. a 20 years old french student in computer engineering, currently studying at ESILV (France, La Défense).'

  socialIcons:
    - name: github
      url: 'https://github.com/strawhattom'
    - name: linkedin
      url: 'https://www.linkedin.com/in/tom-xie-dv/'
  
  ShowBreadCrumbs: true
  ShowReadingTime: true # display reading time
  ShowPostNavLinks: true # display nav in the bottom of the page

menu:
  main:
    - identifier:   projects
      name:       Projects
      url:        /projects
      weight:     10
    - identifier:   archives
      name:       Archives
      url:        /archives
      weight:      20
    - identifier:   contact
      name:       Contact
      url:        /contact
      weight:     30
    - identifier:   tags
      name:       Tags
      url:        /tags
      weight:     40