baseURL: ''
languageCode: en-us
title: Portfolio - Tom X.
theme: PaperMod

languages:
  en:
    languageName: English
    title: Portfolio - Tom X.
    weight: 1
  fr:
    languageName : Français    
    title: Portfolio - Tom X.
    weight: 2

params:
  homeInfoParams:
    Title: 'Welcome to my portfolio'
    Content: 'I am Tom XIE a 20 years old french student in computer engineering, currently studying at ESILV (France, La Défense).'

  socialIcons:
    - name: github
      url: 'https://github.com/strawhattom'
    - name: linkedin
      url: 'https://www.linkedin.com/in/tom-xie-dv/'
  
  ShowBreadCrumbs: true
  ShowReadingTime: true # display reading time
  ShowPostNavLinks: true # display nav in the bottom of the page

menu:
  main:
    - identifier:   projects
      name:       Projects
      url:        /projects
      weight:     10
    - identifier:   archives
      name:       Archives
      url:        /archives
      weight:      20
    - identifier:   contact
      name:       Contact
      url:        /contact
      weight:     30